### ISSUE TITLE
The requested module does not provide an export named 'default'.

### ISSUE THREAD

**Issue by raghuramsadineni** [mdgaziur/EditorJS-LaTeX#3]
I have installed this package using  `yarn add editorjs-latex` and I got this error.

<img width="1174" alt="Screenshot 2023-07-31 at 1 21 18 PM" src="https://github.com/mdgaziur/EditorJS-LaTeX/assets/31440667/e00fc5cf-9545-414f-9a6c-25f0d8fda45e">

I have checked the package source code and it seems to be true:

<img width="1046" alt="Screenshot 2023-07-31 at 1 23 34 PM" src="https://github.com/mdgaziur/EditorJS-LaTeX/assets/31440667/78a2d769-16ae-43b0-bcdc-97d6bd280c70">

I know there are other packages which have fixed this issue but, Can someone update the package in npm registry?

**Comment by mdgaziur** [comment]
Done

**Comment by raghuramsadineni** [comment]
Can you update npm registry again? this new changes are not updated.

**Comment by mdgaziur** [comment]
Fixed in 95f0456. Updated the NPM package.
