### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by nativeanish** [mdgaziur/EditorJS-LaTeX#5]
`Module Tools was skipped because of  Error: Tool «Math» must be a constructor function or an object with function in the «class» property
    value https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    value https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    t https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    c https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    _invoke https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    e https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    n https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    s https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    exports https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
    exports https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js:6
   undefined
`

**Comment by mdgaziur** [comment]
I'm looking into this soon. Might take a while because I'm a bit busy right
now. I apologize for inconsistency in the codebase as it was written when I
really didn't have any idea about what I was doing.

**Comment by mdgaziur** [comment]
Fixed in 95f0456
