### ISSUE TITLE
Can't access readOnly mode in LaTex package

### ISSUE THREAD

**Issue by Raadius** [mdgaziur/EditorJS-LaTeX#7]
Hi, Gaziur! Thank you for your work! With this package it is really great and easy to add latex in editor-js in project!

But I am facing an issue, that readOnly mode is not supported in this package. I checked npm registry here (https://www.npmjs.com/package/editorjs-latex?activeTab=code) and checked code in your project GitHub repo, and I see that it is indeed supported (in index.js line 72-74) but npm package doesn't have it. Can you please update package so that readOnly mode will be accessible?

**Comment by mdgaziur** [comment]
Hi, Raadius! Thanks for reporting the issue. I've published 1.0.5 to NPM. Hopefully this fixes the issue.
